name: brelock
description: "Passwoed manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.1.1
  uuid: ^4.4.2
  meta: ^1.16.0
  otp: ^3.0.1
  file_picker: ^10.3.3
  path_provider: ^2.1.3
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  mailer: ^6.5.0
  connectivity_plus: ^5.0.1
  flutter_localizations: # Добавляем пакет для локализации
      sdk: flutter
  intl: any # Для дополнительных возможностей

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_speed_dial: ^7.0.0
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.1
  build_runner: any
  flutter_gen_runner: any

# Настройки иконки приложения - ДОЛЖЕН БЫТЬ ЗДЕСЬ
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated